version: 0.2
phases:
  install:
    runtime-versions:
        docker: 18
    commands:                                                                 
      - make install
  build:
    commands:
      - make lint
      - make test
  post_build:
    commands:
      - aws s3 sync --delete public s3://dukefeb1
      - echo Testing completed `date`